### ISSUE TITLE
name the standalone framework

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/salon#1]
Picking up from https://github.com/AspenWeb/aspen.py/issues/547 ...

What are we gonna call the standalone framework? Is that Aspen? Or is Aspen just the core?

**Comment by Changaco** [comment]
My original proposal was `aspen-standalone`, but now I'm thinking that `aspen-wsgi` would be better (it's both shorter and more accurate).

**Comment by chadwhitacre** [comment]
`aspen-wsgi` makes me think I'm getting an `environ` dict and a `start_response` callable.

**Comment by Changaco** [comment]
To me it simply evokes compatibility with WSGI.

Other ideas: `aspen-diy`, `aspen-{all,full}`.

**Comment by chadwhitacre** [comment]
Also [floated](https://github.com/AspenWeb/aspen.py/issues/547#issuecomment-184866154) was `aspen` for the standalone web framework and `aspen-core` for the thing that collects dispatch and simplates and is also used by `Flask-Aspen` and `django-aspen`.

**Comment by chadwhitacre** [comment]
Or we could pick a different name like `pando` for the standalone and keep `aspen` for the shared piece.

**Comment by chadwhitacre** [comment]
Here's a photo so crappy it's probably not worth uploading:

![photo on 2-17-16 at 12 59 pm](https://cloud.githubusercontent.com/assets/134455/13119282/5773fad4-d576-11e5-9d44-54b19d8ad560.jpg)

**Comment by chadwhitacre** [comment]
That has all our present repos on it, along with a couple that don't exist yet: **Dispatcher** and **Simplates** (underlined). The two question marks are on **Standalone** (which also doesn't exist yet) and [**Core**](https://github.com/AspenWeb/aspen.py)—those are what we're trying to name here, I take it. Off to the left are the [**rb**](https://github.com/AspenWeb/aspen.rb), [**js**](https://github.com/AspenWeb/aspen.js), and [**go**](https://github.com/AspenWeb/aspen.go) repos. Hovering around Simplates on the right are the [**Vim**](https://github.com/AspenWeb/simplate.vim), [**Emacs**](https://github.com/AspenWeb/simplates.emacs), and [**.org**](https://github.com/AspenWeb/simplates.org) repos related to that. It's too faint to see, but there are dotted lines from [**Plugins**](https://github.com/AspenWeb/aspen.py-plugins) (hovering near Core) that go to Standalone, Core, and Simplates—where are we offering pluggability, exactly? [**Algorithm**](https://github.com/AspenWeb/algorithm.py) and [**Dependency Injection**](https://github.com/AspenWeb/dependency_injection.py) are factored out below Core. [**Filesystem Tree**](https://github.com/AspenWeb/filesystem_tree.py) is floating at the bottom (which project[s] are using it for tests? I forget). [**Salon**](https://github.com/AspenWeb/salon) encompasses the whole.

**Comment by whit537** [comment]
(Previous comment updated w/ links and formatting.)

**Comment by chadwhitacre** [comment]
Aspen 0.x has been a standalone web framework. From an outside world perspective there'd be no expectation that Aspen 1.x wouldn't be, suggesting that we should keep Aspen for the standalone web framework, and use `aspen-core` for the underlying library that also supports `Flask-Aspen` and `django-aspen`.

**Comment by chadwhitacre** [comment]
That's my proposal:
- We keep "Aspen" for the standalone web framework.
- We call the shared library "Aspen Core".

**Comment by Changaco** [comment]
Okay, let's go with that.
