### ISSUE TITLE
Transfer domains?

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/salon#17]
@Changaco I am ready to be done being responsible for the `aspen.io` and `simplates.org` domains. Would you like to be responsible for them? :) Do you think they're valuable for the project?

**Comment by Changaco** [comment]
They're nice domain names, but I'm not sure they're worth the money. If you can transfer them to me without being charged for it, then I'm okay to receive them and handle a possible transition to "free" domains.

**Comment by chadwhitacre** [comment]
I've unlocked the domains for transfer and have emailed you the codes.

I've also turned off auto-renewal, the expiration dates are:

- aspen.io — 24 October 2019 
- simplates.org — 06 May 2020

They are registered at iwantmyname.com, maybe if you have an account there you will be able to transfer them for free?

Let me know if you need anything else from me to take over the domains.

**Comment by Changaco** [comment]
Transfers complete. :+1: 

Aspen's domains are now in Liberapay's iwantmyname account, alongside the old Gittip and Gratipay domains.

**Comment by chadwhitacre** [comment]
Awesome, thanks @Changaco! 💃
