### ISSUE TITLE
Should we keep vendoring dependencies?

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/salon#4]
Picking up from https://github.com/AspenWeb/salon/issues/2#issuecomment-185806278

Do we want all projects who have dependencies to vendor in `virtualenv`, `setuptools`, `pip`, etc? Why do we expect `python` to be installed (since we don't vendor it) but not `virtualenv` and the packaging tools?

The goal of vendoring is to allow offline hacking, right? Why isn't it enough to have a simple reminder in the README that you need to run `make env` or whatever before going offline?

**Comment by chadwhitacre** [comment]
I'm fine to not vendor dependencies on AspenWeb projects.

**Comment by chadwhitacre** [comment]
@pjz is -1 on vendoring.

**Comment by Changaco** [comment]
Okay, then let's drop vendoring entirely, it'll be easier than to use Git LFS. I'll make a PR, and once it's merged we'll rebase 527 on top of master.
