### ISSUE TITLE
Set up donations

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/salon#5]
Now that Aspen is no longer under Gratipay, it needs to be funded separately. I'm going to create a team on Liberapay. I'll leave the possible creation of a team on Gratipay to you @whit537.

**Comment by Changaco** [comment]
Created https://liberapay.com/Aspen/.

**Comment by chadwhitacre** [comment]
Thanks for the invite to the Aspen team on Liberapay, @Changaco. I'm not ready to start actively using Liberapay yet. I'd like to revisit the decision when a) Aspen has significant revenue, and b) I need the money. :-)

**Comment by Changaco** [comment]
Okay. ;-) Should we close this issue or do you want to keep it open?

**Comment by chadwhitacre** [comment]
I'm fine to close for now. :-)

**Comment by chadwhitacre** [comment]
Actually, let's reopen, because I'd still like to set up a Gratipay team. :-)

**Comment by chadwhitacre** [comment]
Gratipay profile at https://gratipay.com/aspen/. Review ticket is https://github.com/gratipay/team-review/issues/176.
