### ISSUE TITLE
Choose an official logo

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/salon#7]
Right now we have two logos: the favicon from http://aspen.io/ which I also used for https://hackerone.com/aspen, and the avatar from https://twitter.com/aspen_io also used on https://gratipay.com/aspen/. We should probably drop one.

**Comment by chadwhitacre** [comment]
I've updated our Gratipay and Twitter accounts to match HackerOne and the favicon.

**Comment by chadwhitacre** [comment]
For posterity:

![c20fd23074965ddc31c6010fdf12c694c66d3836_xtralarge](https://cloud.githubusercontent.com/assets/134455/13507052/e3c61a06-e14e-11e5-9882-fecd928e9f87.png)
